all:
	cd src; make all

install:
	cd module; make install

check: all
	cd test; make check

valCheck: all
	cd test; make valCheck

clean:
	cd src; make clean
	cd test; make clean
	cd module; make clean
