#TODO: uncomment the module stuff once it's working

all:
	cd src; make all
#	cd module; make all

install:
#	cd module; make install

runTest:
	cd test; make test

clean:
	cd src; make clean
	cd test; make clean
#	cd module; make clean

